token: "NzQ3MzU0NTg2NjI4NDg5MjQ2.X0NqMg.ZTDLjCldVVfplaEzRNp-NiKBwOE"

messages:
  discord-to-mc: "&8[&bDiscord&8]&r&f %username%&r&f: &f%message%"
  mc-to-discord: "**[%primarygroup%] %displayname%**: %message%"
  already-linked: "&cYou have already linked your account to %discordname%!"
  already-linking: "&cYou have already requested your custom pin! %pin%"
  linking: "&9&lDISCORD &8»&r &7Your link pin is &b%pin%&7! Message the &b&lChatBot#6226&7 on Discord containing just this code as the message to link your account!"
  linked: "&9&lDISCORD &8»&r &7Your Minecraft account has been linked to Discord! &8(&b&lUSER:&b %username%&r &8/ &b&lID:&b %id%&8)"

guilds:
  guild: "692809364314128394"

channels:
  global-channel: "744279120103604268"
  staff-channel: "731570271852691508"

roles-to-assign-on-link: ["707393522927534091"]
donator-roles-to-assign: [ "Immortal": "746610488384684032", "Overlord":"746610627925246033", "Titan":"746610631125237800", "Legend":"746610633105080360", "Hero":"746610634396794993", "Elite":"746610783865143346" ]